name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t phishoff:latest -f Dockerfile .

      - name: Deploy to Staging Port
        run: |
          docker stop phishoff-staging || true
          docker rm phishoff-staging || true

          docker run -d \
            -p 8001:8000 \
            -v /deployments/models:/model \
            -v /deployments/secrets/.env:/app/.env \
            --env-file /deployments/secrets/.env \
            --gpus all \
            --name phishoff-staging \
            phishoff:latest


      - name: Verify Staging Deployment
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8001/docs | grep "FastAPI"; then
              echo "Staging verification successful"
              exit 0
            fi
            sleep 5
          done
          echo "Staging verification failed"
          exit 1

      - name: Promote to Production
        if: success()
        run: |
          docker stop phishoff || true
          docker rm phishoff || true

          docker run -d \
            -p 8000:8000 \
            -v /deployments/models:/model \
            -v /deployments/secrets/.env:/app/.env \
            --env-file /deployments/secrets/.env \
            --gpus all \
            --name phishoff \
            phishoff:latest

          docker stop phishoff-staging || true
          docker rm phishoff-staging || true

      - name: Verify Production Deployment
        if: success()
        run: |
          sleep 5
          curl -s http://localhost:8000/docs | grep "FastAPI" || exit 1
