name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo cp -r ${{ github.workspace }} /backend
          cd /backend
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart FastAPI service
        run: sudo systemctl restart fastapi

      - name: Verify deployment
        run: |
          sleep 5
          curl -s http://localhost:8000/docs | grep "FastAPI" || exit 1
