name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          # Clean environment
          unset PYTHONPATH
          unset PYTHONHOME
          
          # Create directory with proper permissions
          mkdir -p /backend
          chown -R $USER:$USER /backend
          
          # Copy files as current user
          rsync -a --delete ${{ github.workspace }}/backend/ /backend/
          
          if [ ! -d "/backend/venv" ]; then
            python -m venv /backend/venv
          fi
          
          # Install requirements as current user
          source /backend/venv/bin/activate
          pip install --upgrade pip
          pip install -r /backend/requirements.txt

      - name: Restart FastAPI service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart fastapi

      - name: Verify deployment
        run: |
          sleep 15
          curl -s http://localhost:8000/docs | grep "FastAPI" || exit 1
