name: Test Plasmo Extension

on:
  pull_request:
    branches:
      - main
      - 14-QA-Build-Testing

jobs:
  test:
    runs-on: ubuntu-22.04  # Use stable Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd extension
          npm ci  # Install dependencies using npm ci to ensure clean install from package-lock.json
          npx plasmo --version  # Verify plasmo installation

      - name: Run Plasmo Tests
        run: |
          cd extension
          NODE_OPTIONS="--max-old-space-size=4096" npx plasmo build  # Run plasmo build with increased memory limit
        env:
          PLASMO_PUBLIC_VIRUSTOTAL_API_KEY: ${{ secrets.PLASMO_PUBLIC_VIRUSTOTAL_API_KEY }}
