name: Test Plasmo Extension

on:
  pull_request:
    branches:
      - main
      - 14-QA-Build-Testing

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node 18 instead of Node 20 for compatibility

      - name: Install Dependencies
        run: |
          cd extension
          npm install  # Install dependencies
          npm rebuild  # Rebuild any native modules that could be problematic

      - name: Verify Plasmo Installation
        run: |
          cd extension
          npx plasmo --version  # Verify Plasmo installation

      - name: Run Plasmo Build with Debugging and Increased Memory
        run: |
          cd extension
          DEBUG=* NODE_OPTIONS="--max-old-space-size=8192" npx plasmo build --verbose
        env:
          PLASMO_PUBLIC_VIRUSTOTAL_API_KEY: ${{ secrets.PLASMO_PUBLIC_VIRUSTOTAL_API_KEY }}
